timezone: Australia/Melbourne

permalink: /:title

gtag: G-TH220K7H74
legal_name: Magma Recruiting

collections:
  posts:
    output: true
    permalink: /blog/:title

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-coffeescript

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]

# SCSS
sass:
  style: compressed

# SEO
title: Magma
tagline: Challenging the recruitment process.
description: Project-based work for university students.
logo: /assets/images/favicons/favicon-310.png
social:
  name: Magma
  links:
    - https://www.linkedin.com/company/magma-recruiting/
locale: en-AU